name: Pull Request Lint

on:
  pull_request:
    branches:
      - master
      - develop
      - "releases/**"

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2.1.5
        id: node

      - name: Spellcheck
        run: yarn spellcheck
