name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2.1.5
        id: node

      - name: Install Dependencies
        run: yarn

      - name: Spellcheck
        run: yarn spellcheck
